package config

const (
	DATABASE_CONNECTION_STRING = "DATABASE_CONNECTION_STRING"
	DATABASE_HOST              = "DATABASE_HOST"
	DATABASE_NAME              = "DATABASE_NAME"
	DATABASE_PASS              = "DATABASE_PASS"
	DATABASE_PORT              = "DATABASE_PORT"
	DATABASE_USER              = "DATABASE_USER"

	SECRET_JWT = "SECRET_JWT"
)
